<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <ul>
        <li><a href="https://wolfig.de">www.wolfig.de (im Tab)</a></li>
        <li><a href="https://wolfig.de" target="_blank">www.wolfig.de (im neuen Tab)</a><a</li>
        <li><a href="index.php">Zu index.php</a> </li>
        <li><a href="ordner/Grundstruktur.html">Zu Grundstruktur.html</a> </li>
    </ul>
    <ol style="font-size:100px">
        <li><a id="oben" href="#unten">Ab nach unten</a></li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li>wolfig.de</li>
        <li><a id="unten" href="#oben">Ab nach oben</a></li>
    </ol>

</body>
</html>
